language: python
python:
 - "3.6"

# command to run tests
script:
 - python -m unittest tests.test_bubble_sort
 - python -m unittest tests.test_word_filter
 - python -m unittest tests.test_recursion
 - python -m unittest tests.test_merge_dicts
 - python -m unittest tests.test_calculate_pi
 - python -m unittest tests.test_word_filter
 - python -m unittest tests.test_extract_chinese_characters
 - python -m unittest tests.test_extract_numbers